### PR TITLE
Scala versions

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by ravwojdyla** [comment]
Connected to #19 - now if we release dataflow-flink for 2.10 and 2.11, in sbt we can depend on:

```
"com.dataartisans" %% "flink-dataflow" % flinkDataflowVersion
```

And things will not explode `+assembly`

**Comment by mxm** [comment]
Thanks for the PR! I don't think we need the change_scala_version script. We can simply introduce a property in the root pom to change the Scala version. Please see my changes on the master. You can now just change the `scala.major.version` property when building like so: `mvn clean install -Dscala.major.version=2.11`.

**Comment by ravwojdyla** [comment]
So the way it works right now is that you hard code main artifact name to `flink-dataflow` - that may depend on artifacts from `2.10` and `2.11` ... But how do you choose which `flink-dataflow` to depend on? How does this suppose to work? and afaiu you can't parametrise main artifact name - thus need for script ...

There will be conflicts, like for example:

```
[info] Done updating.
[error]    com.twitter:chill _2.11, _2.10
[trace] Stack trace suppressed: run last scio-flink/*:update for the full output.
[error] (scio-flink/*:update) Conflicting cross-version suffixes in: com.twitter:chill
[error] Total time: 307 s, completed Mar 11, 2016 2:25:09 PM
```

Also this approach is not consistent with the way main flink code gets released ...

Is it clear why this is a problem?

**Comment by mxm** [comment]
You'll have to build `flink-dataflow` for the right Scala version first using the above command. Then you won't run into conflicts with your sbt build. 

Since there is currently no deployed version of flink-dataflow, I didn't want to add a suffix to the module. If you want, you can change the artifact name in your pom.xml to `<artifactId>flink-runner_${scala.major.version}</artifactId>`. Then you'll have builds which carry the Scala major version.

**Comment by ravwojdyla** [comment]
@mxm i had both builds for scala `2.10` and `2.11` for my tests above (also I cleaned up my maven and ivy caches).

For this problem - two solutions worked for me:
 * mark `scope` of all flink artifacts from flink-dataflow as `provided` thus make them non transitive (pull flink artifacts in my own project instead)
 * solutions suggested in #23 

#23 looks consistent with flink to me, thus PR.

**Comment by mxm** [comment]
I thought about this a bit. I would like to remove the Scala dependency of the Runner by setting the Flink dependencies to provided. The Runner itself doesn't use any Scala code. For the examples which depend on Scala, we can create a separate Maven module which has a Scala dependency, but the main code should be Scala free. You would then be able to use the Flink runner regardless of the used Scala version.

**Comment by ravwojdyla** [comment]
@mxm that is one of possible solutions - but don't you think that it has more downsides than having `flink-dataflow-{2.11,2.10}`?

**Comment by mxm** [comment]
Fair enough. Both approaches have its pros and cons. I merged your changes. Thanks!

**Pull request closed without merging**
