### PR TITLE
Scala again

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by ravwojdyla** [comment]
Opening #21 again

**Comment by ravwojdyla** [comment]
If this is good I will submit PR to beam runner too.

**Comment by mxm** [comment]
Thanks for the PR. I think we only need the following change:
```patch
- <artifactId>flink-dataflow</artifactId>
+ <artifactId>flink-dataflow_${scala.major.version}</artifactId>
```

That would generate `flink-dataflow_2.10` or `flink-dataflow_2.11` depending on the used Scala major version. The major version is specified when buliding like `mvn clean install -Dscala.major.version=2.11`.

**Comment by ravwojdyla** [comment]
As mentioned in #21 - afaiu artifactId should not be parametrized, you might be able to hack this around (maybe with architype etc) - but that would be complicated. Why not reuse the flink script, and keep it consistent?

**Comment by mxm** [comment]
Merged in 1cfc4ca4d0fce450aa27a39932f2ba18719c1c67 and 00a0ed2ba532f37b044be63c373829baacc6c214.

**Pull request closed without merging**
