### PR TITLE
Add registrat

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by ravwojdyla** [comment]
This way FlinkRunner ends up in `META-INF/services`:

```
➜  scio git:(flink) ✗ cat META-INF/services/com.google.cloud.dataflow.sdk.runners.PipelineRunnerRegistrar
com.dataartisans.flink.dataflow.FlinkRunnerRegistrar$Runner
com.google.cloud.dataflow.sdk.runners.DataflowPipelineRegistrar$Runner
com.google.cloud.dataflow.sdk.runners.DirectPipelineRegistrar$Runner
```

gets picked up by Dataflow sdk, and thus can be used if you depend on flink-dataflow.

**Comment by mxm** [comment]
Thanks for the PR. Could you explain what you use this for?

**Comment by ravwojdyla** [comment]
This is the mechanism of discovering Dataflow runners read more here -> 

Check out:
 * [this](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/PipelineRunnerRegistrar.java)
 * [and this](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/runners/DataflowPipelineRegistrar.java)

Spark runner is doing something similar ([here](https://github.com/apache/incubator-beam/blob/master/runners/spark/src/main/resources/META-INF/services/com.google.cloud.dataflow.sdk.options.PipelineOptionsRegistrar)) but they hard code they runner, instead of generate them at compile time.

**Comment by ravwojdyla** [comment]
Will submit PR to beam repo too.

**Comment by mxm** [comment]
Thanks for the links. I see that this can be useful. Going to merge in a bit.

**Comment by mxm** [comment]
Merged in a1e1c74b301ad7bda265b63b7df104804cc05c3a.

**Pull request closed without merging**
